unit:
    tc_folder : /test/unit/
    selector  : '*.t'
    regexp    : '.*/(?<testcase>.*?)\s+\.{2,}\s+(?<result>\w+)'
    env:
        HARNESS_OPTIONS       : 'j4:c'
        HARNESS_TIMER         : 1
        HARNESS_PERL_SWITCHES : '-MDevel::Cover=-db,cover_db'
        
component:
    tc_folder : /test/comp/
    selector  : '*.t'
    regexp    : '.*/(?<testcase>.*?)\s+\.{2,}\s+(?<result>\w+)'
    env:
        HARNESS_OPTIONS       : 'j1:c'
        HARNESS_TIMER         : 10
        HARNESS_PERL_SWITCHES : '-MDevel::Cover=-db,cover_db,-ignore,\.t'
        
system:
    exec  : f:\GIT\common\test\system_test\run.bat

static:
    exec  : perlcritic -3
    regexp: 'See page (?<page>\d+) of PBP.  \(Severity: (?<severity>\d)\)'
    
coverage:
    exec      : cover -report html
    

    
